### ISSUE TITLE
This plugin will be unnecessary after Flake8 3.0

### ISSUE THREAD

**Issue by sigmavirus24** [spookylukey/flake8-respect-noqa#3]
In Flake8 3.0 we've taken a lot of control back from pycodestyle/pep8 which has allowed us to enable `# noqa` for all error codes and to further enable `# noqa: <code>,<code>,<code>,...` as needed.

**Comment by spookylukey** [comment]
Excellent, when it is available please let me know and I'll put a note at the top of the README.

**Comment by sigmavirus24** [comment]
I'm hoping to deliver a beta release by the weekend.

**Comment by sigmavirus24** [comment]
3.0.0b1 was released today with this feature! :)
